stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy
  - test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags: 
    - "shell"
  script:
    - echo "Compiling the code..."
    - rm -f pom.xml
    - envsubst < pom.xml.tmpl > pom.xml
    - atlas-clean
    - atlas-package deploy
    - ls -la target
    - echo "Compile complete."
  artifacts:
    name: jar
    paths:
      - target/*.jar
    expire_in: 1 week

